name: Mainstream link checker

on:
  workflow_dispatch:

  schedule:
    - cron: '0 8 1 * *'

permissions:
  contents: write

jobs:
  check-links:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        team:
          - Red
          - Blue
          - Green
          - Yellow
          - Unassigned

    steps:
      - name: Get repository files
        uses: actions/checkout@v5
        with:
          ref: reports

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Run link checker
        run: ruby page_link_checker.rb ${{ matrix.team }}

      - name: List reports
        run: |
          echo "Reports folder contents:"
          ls -lah reports

          echo ""
          echo "All CSV files:"
          find . -name "*.csv"

      - name: Upload report
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.team }}-report
          path: reports/${{ matrix.team }}.csv