name: Mainstream link checker

on:
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository files
        uses: actions/checkout@v5

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Run link checker
        run: ruby page_link_checker.rb

      - name: Upload report
        uses: actions/upload-artifact@v5
        with:
            name: link-check-results
            path: reports/